name: Daily Check

on:
  schedule:
    - cron: 0 9 * * *
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate Matrix
    uses: ./.github/workflows/generate-matrix.yml
  
  check-recent-commits:
    needs: generate-matrix
    name: Check Recent Commits
    uses: ./.github/workflows/check-recent-commits.yml
    with:
      matrix: ${{ needs.generate-matrix.outputs.matrix }}
      
  ci:
    needs: check-recent-commits
    name: CI
    permissions:
      pages: write
      id-token: write
    if: ${{ needs.check-recent-commits.outputs.has-new-commits == 'true' }}
    uses: ./.github/workflows/ci.yml