name: Daily Check

on:
  schedule:
    - cron: 0 9 * * *
  workflow_dispatch:

jobs:
  check-recent-commits:
    name: Check Recent Commits
    uses: ./.github/workflows/check-recent-commits.yml
      
  ci:
    needs: check-recent-commits
    name: CI
    permissions:
      pages: write
      id-token: write
    if: ${{ needs.check-recent-commits.outputs.has-new-commits == 'true' }}
    uses: ./.github/workflows/ci.yml