name: LaTeX Compile All and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDFs
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.TRIPOS_REPO }}

      - name: Install TeX Live
        uses: zauguin/install-texlive@v4
        with:
          package_file: ${{ github.workspace }}/.github/texlive.packages

      - name: Compile Course Files
        run: |
          mkdir webpage
          cd webpage
          mkdir output
          cd ..

          while read course; do
            cd $course

            echo "::group::Compiling $course"
            latexmk -pdflatex -interaction=nonstopmode -file-line-error main.tex
            cp main.pdf "${{ github.workspace }}/webpage/output/$course.pdf"
            echo "::endgroup::"

            cd ${{ github.workspace }}
          done < ${{ github.workspace }}/.github/course.list

      - name: Index Compiled Files
        run: |
          echo "Generating index.html"
          cd webpage
          tree output -H 'output/' -T "Tripos Notes" -o "index.html"

      - name: Upload Static Files as Artifact
        id: upload-webpage
        uses: actions/upload-pages-artifact@v5
        with:
          path: webpage/

  deploy-pages:
    name: Deploy GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-page.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-page
        uses: actions/deploy-pages@v5