name: LaTeX Compile All and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDFs
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.TRIPOS_REPO }}

      - name: Setup TeX Live
        uses: EasonSYC/latex-style-setup@main

      - name: Compile Course Files
        run: |
          mkdir webpage
          cd webpage
          mkdir output
          cd ..

          while read course; do

            cd $course

            echo "::group::Compiling $course"
            
            commit_sha=$(git rev-parse --short HEAD)
            commit_date=$(git log -1 --format=%cd --date=format:%Y%m%d)

            echo "" >> version.tex

            echo "\renewcommand{\DATE}{$commmit_date}" >> version.tex

            echo "\renewcommand{\COMMITSHA}{$commit_sha}" >> version.tex

            latexmk -pdflatex -interaction=nonstopmode -file-line-error main.tex
            cp main.pdf "${{ github.workspace }}/webpage/output/$course-$commit_date-$commit_sha.pdf"

            echo "::endgroup::"

            cd ${{ github.workspace }}
          done < ${{ github.workspace }}/.github/course.list

      - name: Index Compiled Files
        run: |
          echo "Generating index.html"
          cd webpage
          tree output -H 'output/' -T "Tripos Notes" -o "index.html"

      - name: Upload Static Files as Artifact
        id: upload-webpage
        uses: actions/upload-pages-artifact@v5
        with:
          path: webpage/

  deploy-pages:
    name: Deploy GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-page.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-page
        uses: actions/deploy-pages@v5