name: Regular Check

on:
  schedule:
    - cron: '0 15 * * *'
    - timezone: "Europe/London"
  workflow_dispatch:

jobs:
  check-recent-commits:
    name: Check Recent Commits
    uses: ./.github/workflows/check-recent-commits.yml
    with:
      since-hours: 168
      
  ci:
    needs: check-recent-commits
    name: CI
    permissions:
      pages: write
      id-token: write
    if: ${{ needs.check-recent-commits.outputs.has-new-commits == 'true' }}
    uses: ./.github/workflows/ci.yml